// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	task3 "github.com/ShaddockNH3/west2-online-golang-2025-test/task3/biz/router/task3"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	task3.Register(r)
}
