// Code generated by hertz generator.

package main

import (
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task3/biz/dal"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task3/biz/mw"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	dal.Init()

	mw.InitJwt()

	h := server.Default()

	customizedRegister(h)

	h.Spin()
}
