// Code generated by hertz generator.

package main

import (
	handler "github.com/ShaddockNH3/west2-online-golang-2025-test/task3/biz/handler"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task3/biz/handler/task3"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task3/biz/mw"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	v1 := r.Group("/v1")
	{
		userPublicGroup := v1.Group("/user")
		{
			userPublicGroup.POST("/create", task3.CreateUser)
			userPublicGroup.POST("/login", mw.JwtMiddleware.LoginHandler)
		}

		auth := v1.Group("/")
		auth.Use(mw.JwtMiddleware.MiddlewareFunc())
		{
			userPrivateGroup := auth.Group("/user")
			{
				userPrivateGroup.POST("/update/:user_id", task3.UpdateUser)
				userPrivateGroup.POST("/delete/:user_id", task3.DeleteUser)
				userPrivateGroup.POST("/query/", task3.QueryUser)
			}

			todoGroup := auth.Group("/todo_list")
			{
				todoGroup.POST("/create", task3.CreateToDoList)
			}
		}
	}
}
