version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'task4_gorm_mysql'
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "9910:3306"
    environment:
      MYSQL_DATABASE: gorm
      MYSQL_USER: gorm
      MYSQL_PASSWORD: gorm
      MYSQL_ROOT_PASSWORD: "root"
      TZ: Asia/Shanghai
