version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'task4_gorm_mysql'
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "9910:3306"
    environment:
      MYSQL_DATABASE: gorm
      MYSQL_USER: gorm
      MYSQL_PASSWORD: gorm
      MYSQL_ROOT_PASSWORD: "root"
      TZ: Asia/Shanghai
    restart: always

  redis:
    image: 'redis:7'
    container_name: 'task4_gorm_redis'
    ports:
      - "9911:6379"
    volumes:
      # 本地的配置文件，映射到 Redis
      - ./pkg/configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
      # 存放 Redis 的数据
      - ./pkg/data/redis/:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always