// Code generated by hertz generator.

package main

import (
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/dal/db"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/mw/jwt"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/mw/redis"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	// 创建必要的文件夹来存储上传的图片和视频
	utils.CreateDirIfNotExist("./data/")
	utils.CreateDirIfNotExist("./data/avatars/")
	utils.CreateDirIfNotExist("./data/videos/")
	utils.CreateDirIfNotExist("./data/covers/")

	db.Init()
	jwt.InitJwt()
	redis.InitRedis()

	h := server.New(
		server.WithMaxRequestBodySize(20 * 1024 * 1024), // 20MB
	)

	register(h)
	h.Spin()
}
