// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package common

import (
	"fmt"
)

type BaseResponse struct {
	Code string `thrift:"code,1" frugal:"1,default,string" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewBaseResponse() *BaseResponse {
	return &BaseResponse{}
}

func (p *BaseResponse) InitDefault() {
}

func (p *BaseResponse) GetCode() (v string) {
	return p.Code
}

func (p *BaseResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseResponse) SetCode(val string) {
	p.Code = val
}
func (p *BaseResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResponse(%+v)", *p)
}

var fieldIDToName_BaseResponse = map[int16]string{
	1: "code",
	2: "msg",
}

type User struct {
	Id        string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Username  string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Password  string `thrift:"password,3" frugal:"3,default,string" json:"password"`
	AvatarUrl string `thrift:"avatar_url,4" frugal:"4,default,string" json:"avatar_url"`
	CreateAt  string `thrift:"create_at,5" frugal:"5,default,string" json:"create_at"`
	UpdateAt  string `thrift:"update_at,6" frugal:"6,default,string" json:"update_at"`
	DeleteAt  string `thrift:"delete_at,7" frugal:"7,default,string" json:"delete_at"`
	MfaSecret string `thrift:"mfa_secret,8" frugal:"8,default,string" json:"mfa_secret"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v string) {
	return p.Id
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetPassword() (v string) {
	return p.Password
}

func (p *User) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}

func (p *User) GetCreateAt() (v string) {
	return p.CreateAt
}

func (p *User) GetUpdateAt() (v string) {
	return p.UpdateAt
}

func (p *User) GetDeleteAt() (v string) {
	return p.DeleteAt
}

func (p *User) GetMfaSecret() (v string) {
	return p.MfaSecret
}
func (p *User) SetId(val string) {
	p.Id = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetPassword(val string) {
	p.Password = val
}
func (p *User) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}
func (p *User) SetCreateAt(val string) {
	p.CreateAt = val
}
func (p *User) SetUpdateAt(val string) {
	p.UpdateAt = val
}
func (p *User) SetDeleteAt(val string) {
	p.DeleteAt = val
}
func (p *User) SetMfaSecret(val string) {
	p.MfaSecret = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "id",
	2: "username",
	3: "password",
	4: "avatar_url",
	5: "create_at",
	6: "update_at",
	7: "delete_at",
	8: "mfa_secret",
}

type UserDataResponse struct {
	Id        string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Username  string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	AvatarUrl string `thrift:"avatar_url,3" frugal:"3,default,string" json:"avatar_url"`
	CreateAt  string `thrift:"create_at,4" frugal:"4,default,string" json:"create_at"`
	UpdateAt  string `thrift:"update_at,5" frugal:"5,default,string" json:"update_at"`
	DeleteAt  string `thrift:"delete_at,6" frugal:"6,default,string" json:"delete_at"`
}

func NewUserDataResponse() *UserDataResponse {
	return &UserDataResponse{}
}

func (p *UserDataResponse) InitDefault() {
}

func (p *UserDataResponse) GetId() (v string) {
	return p.Id
}

func (p *UserDataResponse) GetUsername() (v string) {
	return p.Username
}

func (p *UserDataResponse) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}

func (p *UserDataResponse) GetCreateAt() (v string) {
	return p.CreateAt
}

func (p *UserDataResponse) GetUpdateAt() (v string) {
	return p.UpdateAt
}

func (p *UserDataResponse) GetDeleteAt() (v string) {
	return p.DeleteAt
}
func (p *UserDataResponse) SetId(val string) {
	p.Id = val
}
func (p *UserDataResponse) SetUsername(val string) {
	p.Username = val
}
func (p *UserDataResponse) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}
func (p *UserDataResponse) SetCreateAt(val string) {
	p.CreateAt = val
}
func (p *UserDataResponse) SetUpdateAt(val string) {
	p.UpdateAt = val
}
func (p *UserDataResponse) SetDeleteAt(val string) {
	p.DeleteAt = val
}

func (p *UserDataResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserDataResponse(%+v)", *p)
}

var fieldIDToName_UserDataResponse = map[int16]string{
	1: "id",
	2: "username",
	3: "avatar_url",
	4: "create_at",
	5: "update_at",
	6: "delete_at",
}

type QrcodeMFAAuthResponse struct {
	Secret string `thrift:"secret,1" frugal:"1,default,string" json:"secret"`
	Qrcode string `thrift:"qrcode,2" frugal:"2,default,string" json:"qrcode"`
}

func NewQrcodeMFAAuthResponse() *QrcodeMFAAuthResponse {
	return &QrcodeMFAAuthResponse{}
}

func (p *QrcodeMFAAuthResponse) InitDefault() {
}

func (p *QrcodeMFAAuthResponse) GetSecret() (v string) {
	return p.Secret
}

func (p *QrcodeMFAAuthResponse) GetQrcode() (v string) {
	return p.Qrcode
}
func (p *QrcodeMFAAuthResponse) SetSecret(val string) {
	p.Secret = val
}
func (p *QrcodeMFAAuthResponse) SetQrcode(val string) {
	p.Qrcode = val
}

func (p *QrcodeMFAAuthResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QrcodeMFAAuthResponse(%+v)", *p)
}

var fieldIDToName_QrcodeMFAAuthResponse = map[int16]string{
	1: "secret",
	2: "qrcode",
}

type Image struct {
	Id               string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	UserId           string `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	Url              string `thrift:"url,3" frugal:"3,default,string" json:"url"`
	OriginalFilename string `thrift:"original_filename,4" frugal:"4,default,string" json:"original_filename"`
	Filepath         string `thrift:"filepath,5" frugal:"5,default,string" json:"filepath"`
	Filesize         int64  `thrift:"filesize,6" frugal:"6,default,i64" json:"filesize"`
	MimeType         string `thrift:"mime_type,7" frugal:"7,default,string" json:"mime_type"`
	CreatedAt        string `thrift:"created_at,8" frugal:"8,default,string" json:"created_at"`
	UpdatedAt        string `thrift:"updated_at,9" frugal:"9,default,string" json:"updated_at"`
	DeletedAt        string `thrift:"deleted_at,10" frugal:"10,default,string" json:"deleted_at"`
}

func NewImage() *Image {
	return &Image{}
}

func (p *Image) InitDefault() {
}

func (p *Image) GetId() (v string) {
	return p.Id
}

func (p *Image) GetUserId() (v string) {
	return p.UserId
}

func (p *Image) GetUrl() (v string) {
	return p.Url
}

func (p *Image) GetOriginalFilename() (v string) {
	return p.OriginalFilename
}

func (p *Image) GetFilepath() (v string) {
	return p.Filepath
}

func (p *Image) GetFilesize() (v int64) {
	return p.Filesize
}

func (p *Image) GetMimeType() (v string) {
	return p.MimeType
}

func (p *Image) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Image) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *Image) GetDeletedAt() (v string) {
	return p.DeletedAt
}
func (p *Image) SetId(val string) {
	p.Id = val
}
func (p *Image) SetUserId(val string) {
	p.UserId = val
}
func (p *Image) SetUrl(val string) {
	p.Url = val
}
func (p *Image) SetOriginalFilename(val string) {
	p.OriginalFilename = val
}
func (p *Image) SetFilepath(val string) {
	p.Filepath = val
}
func (p *Image) SetFilesize(val int64) {
	p.Filesize = val
}
func (p *Image) SetMimeType(val string) {
	p.MimeType = val
}
func (p *Image) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *Image) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *Image) SetDeletedAt(val string) {
	p.DeletedAt = val
}

func (p *Image) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Image(%+v)", *p)
}

var fieldIDToName_Image = map[int16]string{
	1:  "id",
	2:  "user_id",
	3:  "url",
	4:  "original_filename",
	5:  "filepath",
	6:  "filesize",
	7:  "mime_type",
	8:  "created_at",
	9:  "updated_at",
	10: "deleted_at",
}

type VideoItems struct {
	Id           string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	UserId       string `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	VideoUrl     string `thrift:"video_url,3" frugal:"3,default,string" json:"video_url"`
	CoverUrl     string `thrift:"cover_url,4" frugal:"4,default,string" json:"cover_url"`
	Title        string `thrift:"title,5" frugal:"5,default,string" json:"title"`
	Description  string `thrift:"description,6" frugal:"6,default,string" json:"description"`
	VisitCount   int64  `thrift:"visit_count,7" frugal:"7,default,i64" json:"visit_count"`
	LikeCount    int64  `thrift:"like_count,8" frugal:"8,default,i64" json:"like_count"`
	CommentCount int64  `thrift:"comment_count,9" frugal:"9,default,i64" json:"comment_count"`
	CreateAt     string `thrift:"create_at,10" frugal:"10,default,string" json:"create_at"`
	UpdateAt     string `thrift:"update_at,11" frugal:"11,default,string" json:"update_at"`
	DeleteAt     string `thrift:"delete_at,12" frugal:"12,default,string" json:"delete_at"`
}

func NewVideoItems() *VideoItems {
	return &VideoItems{}
}

func (p *VideoItems) InitDefault() {
}

func (p *VideoItems) GetId() (v string) {
	return p.Id
}

func (p *VideoItems) GetUserId() (v string) {
	return p.UserId
}

func (p *VideoItems) GetVideoUrl() (v string) {
	return p.VideoUrl
}

func (p *VideoItems) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *VideoItems) GetTitle() (v string) {
	return p.Title
}

func (p *VideoItems) GetDescription() (v string) {
	return p.Description
}

func (p *VideoItems) GetVisitCount() (v int64) {
	return p.VisitCount
}

func (p *VideoItems) GetLikeCount() (v int64) {
	return p.LikeCount
}

func (p *VideoItems) GetCommentCount() (v int64) {
	return p.CommentCount
}

func (p *VideoItems) GetCreateAt() (v string) {
	return p.CreateAt
}

func (p *VideoItems) GetUpdateAt() (v string) {
	return p.UpdateAt
}

func (p *VideoItems) GetDeleteAt() (v string) {
	return p.DeleteAt
}
func (p *VideoItems) SetId(val string) {
	p.Id = val
}
func (p *VideoItems) SetUserId(val string) {
	p.UserId = val
}
func (p *VideoItems) SetVideoUrl(val string) {
	p.VideoUrl = val
}
func (p *VideoItems) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *VideoItems) SetTitle(val string) {
	p.Title = val
}
func (p *VideoItems) SetDescription(val string) {
	p.Description = val
}
func (p *VideoItems) SetVisitCount(val int64) {
	p.VisitCount = val
}
func (p *VideoItems) SetLikeCount(val int64) {
	p.LikeCount = val
}
func (p *VideoItems) SetCommentCount(val int64) {
	p.CommentCount = val
}
func (p *VideoItems) SetCreateAt(val string) {
	p.CreateAt = val
}
func (p *VideoItems) SetUpdateAt(val string) {
	p.UpdateAt = val
}
func (p *VideoItems) SetDeleteAt(val string) {
	p.DeleteAt = val
}

func (p *VideoItems) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoItems(%+v)", *p)
}

var fieldIDToName_VideoItems = map[int16]string{
	1:  "id",
	2:  "user_id",
	3:  "video_url",
	4:  "cover_url",
	5:  "title",
	6:  "description",
	7:  "visit_count",
	8:  "like_count",
	9:  "comment_count",
	10: "create_at",
	11: "update_at",
	12: "delete_at",
}

type VideoDataForPopularResponse struct {
	Items []*VideoItems `thrift:"items,1" frugal:"1,default,list<VideoItems>" json:"items"`
}

func NewVideoDataForPopularResponse() *VideoDataForPopularResponse {
	return &VideoDataForPopularResponse{}
}

func (p *VideoDataForPopularResponse) InitDefault() {
}

func (p *VideoDataForPopularResponse) GetItems() (v []*VideoItems) {
	return p.Items
}
func (p *VideoDataForPopularResponse) SetItems(val []*VideoItems) {
	p.Items = val
}

func (p *VideoDataForPopularResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoDataForPopularResponse(%+v)", *p)
}

var fieldIDToName_VideoDataForPopularResponse = map[int16]string{
	1: "items",
}

type VideoDataForListResponse struct {
	Items []*VideoItems `thrift:"items,1" frugal:"1,default,list<VideoItems>" json:"items"`
	Total int64         `thrift:"total,2" frugal:"2,default,i64" json:"total"`
}

func NewVideoDataForListResponse() *VideoDataForListResponse {
	return &VideoDataForListResponse{}
}

func (p *VideoDataForListResponse) InitDefault() {
}

func (p *VideoDataForListResponse) GetItems() (v []*VideoItems) {
	return p.Items
}

func (p *VideoDataForListResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *VideoDataForListResponse) SetItems(val []*VideoItems) {
	p.Items = val
}
func (p *VideoDataForListResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *VideoDataForListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoDataForListResponse(%+v)", *p)
}

var fieldIDToName_VideoDataForListResponse = map[int16]string{
	1: "items",
	2: "total",
}

type LikeItems struct {
	Id           string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	UserId       string `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	LikeableID   string `thrift:"LikeableID,3" frugal:"3,default,string" json:"LikeableID"`
	LikeableType string `thrift:"LikeableType,4" frugal:"4,default,string" json:"LikeableType"`
	CreateAt     string `thrift:"create_at,5" frugal:"5,default,string" json:"create_at"`
	UpdateAt     string `thrift:"update_at,6" frugal:"6,default,string" json:"update_at"`
	DeleteAt     string `thrift:"delete_at,7" frugal:"7,default,string" json:"delete_at"`
}

func NewLikeItems() *LikeItems {
	return &LikeItems{}
}

func (p *LikeItems) InitDefault() {
}

func (p *LikeItems) GetId() (v string) {
	return p.Id
}

func (p *LikeItems) GetUserId() (v string) {
	return p.UserId
}

func (p *LikeItems) GetLikeableID() (v string) {
	return p.LikeableID
}

func (p *LikeItems) GetLikeableType() (v string) {
	return p.LikeableType
}

func (p *LikeItems) GetCreateAt() (v string) {
	return p.CreateAt
}

func (p *LikeItems) GetUpdateAt() (v string) {
	return p.UpdateAt
}

func (p *LikeItems) GetDeleteAt() (v string) {
	return p.DeleteAt
}
func (p *LikeItems) SetId(val string) {
	p.Id = val
}
func (p *LikeItems) SetUserId(val string) {
	p.UserId = val
}
func (p *LikeItems) SetLikeableID(val string) {
	p.LikeableID = val
}
func (p *LikeItems) SetLikeableType(val string) {
	p.LikeableType = val
}
func (p *LikeItems) SetCreateAt(val string) {
	p.CreateAt = val
}
func (p *LikeItems) SetUpdateAt(val string) {
	p.UpdateAt = val
}
func (p *LikeItems) SetDeleteAt(val string) {
	p.DeleteAt = val
}

func (p *LikeItems) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LikeItems(%+v)", *p)
}

var fieldIDToName_LikeItems = map[int16]string{
	1: "id",
	2: "user_id",
	3: "LikeableID",
	4: "LikeableType",
	5: "create_at",
	6: "update_at",
	7: "delete_at",
}

type LikeVideoDTO struct {
	ID           string `thrift:"ID,1" frugal:"1,default,string" json:"ID"`
	UserID       string `thrift:"UserID,2" frugal:"2,default,string" json:"UserID"`
	VideoURL     string `thrift:"VideoURL,3" frugal:"3,default,string" json:"VideoURL"`
	CoverURL     string `thrift:"CoverURL,4" frugal:"4,default,string" json:"CoverURL"`
	Title        string `thrift:"Title,5" frugal:"5,default,string" json:"Title"`
	Description  string `thrift:"Description,6" frugal:"6,default,string" json:"Description"`
	VisitCount   int64  `thrift:"VisitCount,7" frugal:"7,default,i64" json:"VisitCount"`
	LikeCount    int64  `thrift:"LikeCount,8" frugal:"8,default,i64" json:"LikeCount"`
	CommentCount int64  `thrift:"CommentCount,9" frugal:"9,default,i64" json:"CommentCount"`
	CreatedAt    string `thrift:"CreatedAt,10" frugal:"10,default,string" json:"CreatedAt"`
	UpdatedAt    string `thrift:"UpdatedAt,11" frugal:"11,default,string" json:"UpdatedAt"`
	DeletedAt    string `thrift:"DeletedAt,12" frugal:"12,default,string" json:"DeletedAt"`
}

func NewLikeVideoDTO() *LikeVideoDTO {
	return &LikeVideoDTO{}
}

func (p *LikeVideoDTO) InitDefault() {
}

func (p *LikeVideoDTO) GetID() (v string) {
	return p.ID
}

func (p *LikeVideoDTO) GetUserID() (v string) {
	return p.UserID
}

func (p *LikeVideoDTO) GetVideoURL() (v string) {
	return p.VideoURL
}

func (p *LikeVideoDTO) GetCoverURL() (v string) {
	return p.CoverURL
}

func (p *LikeVideoDTO) GetTitle() (v string) {
	return p.Title
}

func (p *LikeVideoDTO) GetDescription() (v string) {
	return p.Description
}

func (p *LikeVideoDTO) GetVisitCount() (v int64) {
	return p.VisitCount
}

func (p *LikeVideoDTO) GetLikeCount() (v int64) {
	return p.LikeCount
}

func (p *LikeVideoDTO) GetCommentCount() (v int64) {
	return p.CommentCount
}

func (p *LikeVideoDTO) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *LikeVideoDTO) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *LikeVideoDTO) GetDeletedAt() (v string) {
	return p.DeletedAt
}
func (p *LikeVideoDTO) SetID(val string) {
	p.ID = val
}
func (p *LikeVideoDTO) SetUserID(val string) {
	p.UserID = val
}
func (p *LikeVideoDTO) SetVideoURL(val string) {
	p.VideoURL = val
}
func (p *LikeVideoDTO) SetCoverURL(val string) {
	p.CoverURL = val
}
func (p *LikeVideoDTO) SetTitle(val string) {
	p.Title = val
}
func (p *LikeVideoDTO) SetDescription(val string) {
	p.Description = val
}
func (p *LikeVideoDTO) SetVisitCount(val int64) {
	p.VisitCount = val
}
func (p *LikeVideoDTO) SetLikeCount(val int64) {
	p.LikeCount = val
}
func (p *LikeVideoDTO) SetCommentCount(val int64) {
	p.CommentCount = val
}
func (p *LikeVideoDTO) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *LikeVideoDTO) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *LikeVideoDTO) SetDeletedAt(val string) {
	p.DeletedAt = val
}

func (p *LikeVideoDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LikeVideoDTO(%+v)", *p)
}

var fieldIDToName_LikeVideoDTO = map[int16]string{
	1:  "ID",
	2:  "UserID",
	3:  "VideoURL",
	4:  "CoverURL",
	5:  "Title",
	6:  "Description",
	7:  "VisitCount",
	8:  "LikeCount",
	9:  "CommentCount",
	10: "CreatedAt",
	11: "UpdatedAt",
	12: "DeletedAt",
}

type LikeListResponse struct {
	Items []*LikeVideoDTO `thrift:"items,1" frugal:"1,default,list<LikeVideoDTO>" json:"items"`
}

func NewLikeListResponse() *LikeListResponse {
	return &LikeListResponse{}
}

func (p *LikeListResponse) InitDefault() {
}

func (p *LikeListResponse) GetItems() (v []*LikeVideoDTO) {
	return p.Items
}
func (p *LikeListResponse) SetItems(val []*LikeVideoDTO) {
	p.Items = val
}

func (p *LikeListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LikeListResponse(%+v)", *p)
}

var fieldIDToName_LikeListResponse = map[int16]string{
	1: "items",
}

type CommentItems struct {
	Id         string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	UserId     string `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	VideoId    string `thrift:"video_id,3" frugal:"3,default,string" json:"video_id"`
	ParentId   string `thrift:"parent_id,4" frugal:"4,default,string" json:"parent_id"`
	LikeCount  int64  `thrift:"like_count,5" frugal:"5,default,i64" json:"like_count"`
	ChildCount int64  `thrift:"child_count,6" frugal:"6,default,i64" json:"child_count"`
	Content    string `thrift:"content,7" frugal:"7,default,string" json:"content"`
	CreatedAt  string `thrift:"created_at,8" frugal:"8,default,string" json:"created_at"`
	UpdatedAt  string `thrift:"updated_at,9" frugal:"9,default,string" json:"updated_at"`
	DeletedAt  string `thrift:"deleted_at,10" frugal:"10,default,string" json:"deleted_at"`
}

func NewCommentItems() *CommentItems {
	return &CommentItems{}
}

func (p *CommentItems) InitDefault() {
}

func (p *CommentItems) GetId() (v string) {
	return p.Id
}

func (p *CommentItems) GetUserId() (v string) {
	return p.UserId
}

func (p *CommentItems) GetVideoId() (v string) {
	return p.VideoId
}

func (p *CommentItems) GetParentId() (v string) {
	return p.ParentId
}

func (p *CommentItems) GetLikeCount() (v int64) {
	return p.LikeCount
}

func (p *CommentItems) GetChildCount() (v int64) {
	return p.ChildCount
}

func (p *CommentItems) GetContent() (v string) {
	return p.Content
}

func (p *CommentItems) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *CommentItems) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *CommentItems) GetDeletedAt() (v string) {
	return p.DeletedAt
}
func (p *CommentItems) SetId(val string) {
	p.Id = val
}
func (p *CommentItems) SetUserId(val string) {
	p.UserId = val
}
func (p *CommentItems) SetVideoId(val string) {
	p.VideoId = val
}
func (p *CommentItems) SetParentId(val string) {
	p.ParentId = val
}
func (p *CommentItems) SetLikeCount(val int64) {
	p.LikeCount = val
}
func (p *CommentItems) SetChildCount(val int64) {
	p.ChildCount = val
}
func (p *CommentItems) SetContent(val string) {
	p.Content = val
}
func (p *CommentItems) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *CommentItems) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *CommentItems) SetDeletedAt(val string) {
	p.DeletedAt = val
}

func (p *CommentItems) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentItems(%+v)", *p)
}

var fieldIDToName_CommentItems = map[int16]string{
	1:  "id",
	2:  "user_id",
	3:  "video_id",
	4:  "parent_id",
	5:  "like_count",
	6:  "child_count",
	7:  "content",
	8:  "created_at",
	9:  "updated_at",
	10: "deleted_at",
}

type CommentDataForListResponse struct {
	Items []*CommentItems `thrift:"items,1" frugal:"1,default,list<CommentItems>" json:"items"`
}

func NewCommentDataForListResponse() *CommentDataForListResponse {
	return &CommentDataForListResponse{}
}

func (p *CommentDataForListResponse) InitDefault() {
}

func (p *CommentDataForListResponse) GetItems() (v []*CommentItems) {
	return p.Items
}
func (p *CommentDataForListResponse) SetItems(val []*CommentItems) {
	p.Items = val
}

func (p *CommentDataForListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentDataForListResponse(%+v)", *p)
}

var fieldIDToName_CommentDataForListResponse = map[int16]string{
	1: "items",
}

type SocialItems struct {
	Id         string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	FollowerId string `thrift:"follower_id,2" frugal:"2,default,string" json:"follower_id"`
	FollowedId string `thrift:"followed_id,3" frugal:"3,default,string" json:"followed_id"`
	CreatedAt  string `thrift:"created_at,4" frugal:"4,default,string" json:"created_at"`
	UpdatedAt  string `thrift:"updated_at,5" frugal:"5,default,string" json:"updated_at"`
	DeletedAt  string `thrift:"deleted_at,6" frugal:"6,default,string" json:"deleted_at"`
}

func NewSocialItems() *SocialItems {
	return &SocialItems{}
}

func (p *SocialItems) InitDefault() {
}

func (p *SocialItems) GetId() (v string) {
	return p.Id
}

func (p *SocialItems) GetFollowerId() (v string) {
	return p.FollowerId
}

func (p *SocialItems) GetFollowedId() (v string) {
	return p.FollowedId
}

func (p *SocialItems) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *SocialItems) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *SocialItems) GetDeletedAt() (v string) {
	return p.DeletedAt
}
func (p *SocialItems) SetId(val string) {
	p.Id = val
}
func (p *SocialItems) SetFollowerId(val string) {
	p.FollowerId = val
}
func (p *SocialItems) SetFollowedId(val string) {
	p.FollowedId = val
}
func (p *SocialItems) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *SocialItems) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *SocialItems) SetDeletedAt(val string) {
	p.DeletedAt = val
}

func (p *SocialItems) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialItems(%+v)", *p)
}

var fieldIDToName_SocialItems = map[int16]string{
	1: "id",
	2: "follower_id",
	3: "followed_id",
	4: "created_at",
	5: "updated_at",
	6: "deleted_at",
}

type SocialDTO struct {
	Id        string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Username  string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	AvatarUrl string `thrift:"avatar_url,3" frugal:"3,default,string" json:"avatar_url"`
}

func NewSocialDTO() *SocialDTO {
	return &SocialDTO{}
}

func (p *SocialDTO) InitDefault() {
}

func (p *SocialDTO) GetId() (v string) {
	return p.Id
}

func (p *SocialDTO) GetUsername() (v string) {
	return p.Username
}

func (p *SocialDTO) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *SocialDTO) SetId(val string) {
	p.Id = val
}
func (p *SocialDTO) SetUsername(val string) {
	p.Username = val
}
func (p *SocialDTO) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *SocialDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialDTO(%+v)", *p)
}

var fieldIDToName_SocialDTO = map[int16]string{
	1: "id",
	2: "username",
	3: "avatar_url",
}

type SocialDataForListResponse struct {
	Items []*SocialDTO `thrift:"items,1" frugal:"1,default,list<SocialDTO>" json:"items"`
	Total int64        `thrift:"total,2" frugal:"2,default,i64" json:"total"`
}

func NewSocialDataForListResponse() *SocialDataForListResponse {
	return &SocialDataForListResponse{}
}

func (p *SocialDataForListResponse) InitDefault() {
}

func (p *SocialDataForListResponse) GetItems() (v []*SocialDTO) {
	return p.Items
}

func (p *SocialDataForListResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *SocialDataForListResponse) SetItems(val []*SocialDTO) {
	p.Items = val
}
func (p *SocialDataForListResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *SocialDataForListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialDataForListResponse(%+v)", *p)
}

var fieldIDToName_SocialDataForListResponse = map[int16]string{
	1: "items",
	2: "total",
}
