// Code generated by Kitex v0.15.2. DO NOT EDIT.

package userservice

import (
	"context"
	user "github.com/ShaddockNH3/west2-online-golang-2025-test/task5/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RegisterUser(ctx context.Context, req *user.RegisterUserRequest, callOptions ...callopt.Option) (r *user.RegisterUserResponse, err error)
	LoginUser(ctx context.Context, req *user.LoginUserRequest, callOptions ...callopt.Option) (r *user.LoginUserResponse, err error)
	InfoUser(ctx context.Context, req *user.InfoUserRequest, callOptions ...callopt.Option) (r *user.InfoUserResponse, err error)
	AvatarUploadUser(ctx context.Context, req *user.AvatarUploadUserRequest, callOptions ...callopt.Option) (r *user.AvatarUploadUserResponse, err error)
	QrcodeMFAAuth(ctx context.Context, req *user.QrcodeMFAAuthRequest, callOptions ...callopt.Option) (r *user.QrcodeMFAAuthResponse, err error)
	BindMFAAuth(ctx context.Context, req *user.BindMFAAuthRequest, callOptions ...callopt.Option) (r *user.BindMFAAuthResponse, err error)
	SearchImage(ctx context.Context, req *user.SearchImageRequest, callOptions ...callopt.Option) (r *user.SearchImageResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) RegisterUser(ctx context.Context, req *user.RegisterUserRequest, callOptions ...callopt.Option) (r *user.RegisterUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterUser(ctx, req)
}

func (p *kUserServiceClient) LoginUser(ctx context.Context, req *user.LoginUserRequest, callOptions ...callopt.Option) (r *user.LoginUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LoginUser(ctx, req)
}

func (p *kUserServiceClient) InfoUser(ctx context.Context, req *user.InfoUserRequest, callOptions ...callopt.Option) (r *user.InfoUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InfoUser(ctx, req)
}

func (p *kUserServiceClient) AvatarUploadUser(ctx context.Context, req *user.AvatarUploadUserRequest, callOptions ...callopt.Option) (r *user.AvatarUploadUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AvatarUploadUser(ctx, req)
}

func (p *kUserServiceClient) QrcodeMFAAuth(ctx context.Context, req *user.QrcodeMFAAuthRequest, callOptions ...callopt.Option) (r *user.QrcodeMFAAuthResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QrcodeMFAAuth(ctx, req)
}

func (p *kUserServiceClient) BindMFAAuth(ctx context.Context, req *user.BindMFAAuthRequest, callOptions ...callopt.Option) (r *user.BindMFAAuthResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindMFAAuth(ctx, req)
}

func (p *kUserServiceClient) SearchImage(ctx context.Context, req *user.SearchImageRequest, callOptions ...callopt.Option) (r *user.SearchImageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchImage(ctx, req)
}
