// Code generated by Kitex v0.15.2. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	user "github.com/ShaddockNH3/west2-online-golang-2025-test/task5/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"RegisterUser": kitex.NewMethodInfo(
		registerUserHandler,
		newUserServiceRegisterUserArgs,
		newUserServiceRegisterUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LoginUser": kitex.NewMethodInfo(
		loginUserHandler,
		newUserServiceLoginUserArgs,
		newUserServiceLoginUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"InfoUser": kitex.NewMethodInfo(
		infoUserHandler,
		newUserServiceInfoUserArgs,
		newUserServiceInfoUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AvatarUploadUser": kitex.NewMethodInfo(
		avatarUploadUserHandler,
		newUserServiceAvatarUploadUserArgs,
		newUserServiceAvatarUploadUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QrcodeMFAAuth": kitex.NewMethodInfo(
		qrcodeMFAAuthHandler,
		newUserServiceQrcodeMFAAuthArgs,
		newUserServiceQrcodeMFAAuthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindMFAAuth": kitex.NewMethodInfo(
		bindMFAAuthHandler,
		newUserServiceBindMFAAuthArgs,
		newUserServiceBindMFAAuthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchImage": kitex.NewMethodInfo(
		searchImageHandler,
		newUserServiceSearchImageArgs,
		newUserServiceSearchImageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterUserArgs)
	realResult := result.(*user.UserServiceRegisterUserResult)
	success, err := handler.(user.UserService).RegisterUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterUserArgs() interface{} {
	return user.NewUserServiceRegisterUserArgs()
}

func newUserServiceRegisterUserResult() interface{} {
	return user.NewUserServiceRegisterUserResult()
}

func loginUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginUserArgs)
	realResult := result.(*user.UserServiceLoginUserResult)
	success, err := handler.(user.UserService).LoginUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginUserArgs() interface{} {
	return user.NewUserServiceLoginUserArgs()
}

func newUserServiceLoginUserResult() interface{} {
	return user.NewUserServiceLoginUserResult()
}

func infoUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceInfoUserArgs)
	realResult := result.(*user.UserServiceInfoUserResult)
	success, err := handler.(user.UserService).InfoUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceInfoUserArgs() interface{} {
	return user.NewUserServiceInfoUserArgs()
}

func newUserServiceInfoUserResult() interface{} {
	return user.NewUserServiceInfoUserResult()
}

func avatarUploadUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAvatarUploadUserArgs)
	realResult := result.(*user.UserServiceAvatarUploadUserResult)
	success, err := handler.(user.UserService).AvatarUploadUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAvatarUploadUserArgs() interface{} {
	return user.NewUserServiceAvatarUploadUserArgs()
}

func newUserServiceAvatarUploadUserResult() interface{} {
	return user.NewUserServiceAvatarUploadUserResult()
}

func qrcodeMFAAuthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceQrcodeMFAAuthArgs)
	realResult := result.(*user.UserServiceQrcodeMFAAuthResult)
	success, err := handler.(user.UserService).QrcodeMFAAuth(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceQrcodeMFAAuthArgs() interface{} {
	return user.NewUserServiceQrcodeMFAAuthArgs()
}

func newUserServiceQrcodeMFAAuthResult() interface{} {
	return user.NewUserServiceQrcodeMFAAuthResult()
}

func bindMFAAuthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceBindMFAAuthArgs)
	realResult := result.(*user.UserServiceBindMFAAuthResult)
	success, err := handler.(user.UserService).BindMFAAuth(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceBindMFAAuthArgs() interface{} {
	return user.NewUserServiceBindMFAAuthArgs()
}

func newUserServiceBindMFAAuthResult() interface{} {
	return user.NewUserServiceBindMFAAuthResult()
}

func searchImageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSearchImageArgs)
	realResult := result.(*user.UserServiceSearchImageResult)
	success, err := handler.(user.UserService).SearchImage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSearchImageArgs() interface{} {
	return user.NewUserServiceSearchImageArgs()
}

func newUserServiceSearchImageResult() interface{} {
	return user.NewUserServiceSearchImageResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RegisterUser(ctx context.Context, req *user.RegisterUserRequest) (r *user.RegisterUserResponse, err error) {
	var _args user.UserServiceRegisterUserArgs
	_args.Req = req
	var _result user.UserServiceRegisterUserResult
	if err = p.c.Call(ctx, "RegisterUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginUser(ctx context.Context, req *user.LoginUserRequest) (r *user.LoginUserResponse, err error) {
	var _args user.UserServiceLoginUserArgs
	_args.Req = req
	var _result user.UserServiceLoginUserResult
	if err = p.c.Call(ctx, "LoginUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InfoUser(ctx context.Context, req *user.InfoUserRequest) (r *user.InfoUserResponse, err error) {
	var _args user.UserServiceInfoUserArgs
	_args.Req = req
	var _result user.UserServiceInfoUserResult
	if err = p.c.Call(ctx, "InfoUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AvatarUploadUser(ctx context.Context, req *user.AvatarUploadUserRequest) (r *user.AvatarUploadUserResponse, err error) {
	var _args user.UserServiceAvatarUploadUserArgs
	_args.Req = req
	var _result user.UserServiceAvatarUploadUserResult
	if err = p.c.Call(ctx, "AvatarUploadUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QrcodeMFAAuth(ctx context.Context, req *user.QrcodeMFAAuthRequest) (r *user.QrcodeMFAAuthResponse, err error) {
	var _args user.UserServiceQrcodeMFAAuthArgs
	_args.Req = req
	var _result user.UserServiceQrcodeMFAAuthResult
	if err = p.c.Call(ctx, "QrcodeMFAAuth", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindMFAAuth(ctx context.Context, req *user.BindMFAAuthRequest) (r *user.BindMFAAuthResponse, err error) {
	var _args user.UserServiceBindMFAAuthArgs
	_args.Req = req
	var _result user.UserServiceBindMFAAuthResult
	if err = p.c.Call(ctx, "BindMFAAuth", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchImage(ctx context.Context, req *user.SearchImageRequest) (r *user.SearchImageResponse, err error) {
	var _args user.UserServiceSearchImageArgs
	_args.Req = req
	var _result user.UserServiceSearchImageResult
	if err = p.c.Call(ctx, "SearchImage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
