// Code generated by hertz generator.

package video

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _popularMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _popularvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}
