// Code generated by hertz generator.

package video

import (
	"context"

	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/mw/jwt"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _popularMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _popularvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishvideoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		TokenTransferMiddleware(),
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func TokenTransferMiddleware() app.HandlerFunc {
	return func(c context.Context, ctx *app.RequestContext) {
		accessToken := string(ctx.Request.Header.Peek("Access-Token"))

		if accessToken != "" {
			ctx.Request.Header.Set("Authorization", "Bearer "+accessToken)
		}

		ctx.Next(c)
	}
}
