// Code generated by hertz generator.

package user

import (
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/mw/jwt"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infouserMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _loginuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registeruserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avataruploaduserMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bindmfaauthMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _qrcodemfaauthMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.AccessTokenJwtMiddleware.MiddlewareFunc(),
	}
}

func _imageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchimageMw() []app.HandlerFunc {
	// your code...
	return nil
}
