// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/mw/jwt"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infouserMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		TokenTransferMiddleware(),
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _loginuserMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.LoginHandler,
	}
}

func _registeruserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avataruploaduserMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		TokenTransferMiddleware(),
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func TokenTransferMiddleware() app.HandlerFunc {
	return func(c context.Context, ctx *app.RequestContext) {
		accessToken := string(ctx.Request.Header.Peek("Access-Token"))

		if accessToken != "" {
			ctx.Request.Header.Set("Authorization", "Bearer "+accessToken)
		}

		ctx.Next(c)
	}
}