// Code generated by hertz generator.

package social

import (
	"context"

	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/mw/jwt"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		TokenTransferMiddleware(),
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _listfollowerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfollowingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfriendsMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		TokenTransferMiddleware(),
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _actionrelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func TokenTransferMiddleware() app.HandlerFunc {
	return func(c context.Context, ctx *app.RequestContext) {
		accessToken := string(ctx.Request.Header.Peek("Access-Token"))

		if accessToken != "" {
			ctx.Request.Header.Set("Authorization", "Bearer "+accessToken)
		}

		ctx.Next(c)
	}
}
