// Code generated by hertz generator.

package video

import (
	"context"

	video "github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/model/video"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PublishVideo .
// @router /v1/video/publish/ [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PublishVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListVideo .
// @router /v1/video/list/ [GET]
func ListVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.ListVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.ListVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// PopularVideo .
// @router /v1/video/popular/ [GET]
func PopularVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PopularVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PopularVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// SearchVideo .
// @router /v1/video/search/ [POST]
func SearchVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.SearchVideoResponse)

	c.JSON(consts.StatusOK, resp)
}
