// Code generated by hertz generator.

package video

import (
	"context"
	"fmt"

	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/model/common"
	video "github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/model/video"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/pack"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/service/video_service"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/pkg/constants"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/pkg/errno"
	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PublishVideo .
// @router /v1/video/publish/ [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := new(video.PublishVideoResponse)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 获取当前用户ID
	currentUserID, exists := c.Get(constants.ContextCurrentUserKey)
	if !exists {
		resp := new(video.PublishVideoResponse)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  errno.UnableToRetrieveUserInfoErr.ErrMsg,
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 处理视频文件上传，并且处理封面生成
	// 这部分的逻辑需要封装，并且重构为分布式
	// 视频分布传输也是保存在本地先，而不是采用其他技术部署到云盘上
	// 未来可以考虑使用对象存储服务，使用MinIO等
	// 目前是需要一个函数返回——
	// currentVideo,currentCover（文件本身，这里改成使用uuid在service层生成）

	// 这个函数处理视频上传，返回视频本身，暂时还是保存在本地的单片上传
	savePath, currentVideo, err := utils.UploadVideo(c, currentUserID.(string))

	if err != nil {
		resp := new(video.PublishVideoResponse)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 这个函数处理封面生成，返回封面的基本参数
	coverFilename, coverSavePath, coverSize, err := utils.GenerateVideoCover(savePath, currentUserID.(string), currentVideo.Filename)
	if err != nil {
		resp := new(video.PublishVideoResponse)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 调用服务，创建视频
	VideoService := video_service.NewVideoService(ctx)
	err = VideoService.CreateVideo(currentUserID.(string), currentVideo, coverFilename, coverSavePath, coverSize, &req)

	resp := new(video.PublishVideoResponse)

	if err != nil {
		e := errno.ConvertErr(err)

		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  e.ErrMsg,
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	resp.Base = &common.BaseResponse{
		Code: fmt.Sprintf("%d", errno.Success.ErrCode), // 10000
		Msg:  errno.Success.ErrMsg,                     // "success"
	}

	c.JSON(consts.StatusOK, resp)
}

// ListVideo .
// @router /v1/video/list/ [GET]
func ListVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.ListVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := new(video.ListVideoResponse)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 调用服务，获取视频列表
	VideoService := video_service.NewVideoService(ctx)
	videos, total, err := VideoService.ListVideos(&req)

	if err != nil {
		resp := new(video.ListVideoResponse)
		e := errno.ConvertErr(err)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  e.ErrMsg,
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 返回响应
	resp := new(video.ListVideoResponse)
	resp.Base = &common.BaseResponse{
		Code: fmt.Sprintf("%d", errno.Success.ErrCode), // 10000
		Msg:  errno.Success.ErrMsg,                     // "success"
	}
	resp.Data = &common.VideoDataForListResponse{
		Items: pack.Videos(videos),
		Total: total,
	}

	c.JSON(consts.StatusOK, resp)
}

// PopularVideo .
// @router /v1/video/popular/ [GET]
func PopularVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PopularVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := new(video.PopularVideoResponse)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	VideoService := video_service.NewVideoService(ctx)
	videos, err := VideoService.PopularVideos(&req)

	if err != nil {
		resp := new(video.PopularVideoResponse)
		e := errno.ConvertErr(err)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  e.ErrMsg,
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 返回响应
	resp := new(video.PopularVideoResponse)
	resp.Base = &common.BaseResponse{
		Code: fmt.Sprintf("%d", errno.Success.ErrCode), // 10000
		Msg:  errno.Success.ErrMsg,                     // "success"
	}
	resp.Data = &common.VideoDataForPopularResponse{
		Items: pack.Videos(videos),
	}

	c.JSON(consts.StatusOK, resp)
}

// SearchVideo .
// @router /v1/video/search/ [POST]
func SearchVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := new(video.SearchVideoResponse)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	VideoService := video_service.NewVideoService(ctx)
	videos, total, err := VideoService.SearchVideos(&req)

	if err != nil {
		resp := new(video.SearchVideoResponse)
		e := errno.ConvertErr(err)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  e.ErrMsg,
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 返回响应
	resp := new(video.SearchVideoResponse)
	resp.Base = &common.BaseResponse{
		Code: fmt.Sprintf("%d", errno.Success.ErrCode), // 10000
		Msg:  errno.Success.ErrMsg,                     // "success"
	}
	resp.Data = &common.VideoDataForListResponse{
		Items: pack.Videos(videos),
		Total: total,
	}

	c.JSON(consts.StatusOK, resp)
}

// FeedVideo .
// @router /v1/video/feed/ [GET]
func FeedVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.FeedVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := new(video.FeedVideoResponse)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  err.Error(),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	VideoService := video_service.NewVideoService(ctx)
	videos, err := VideoService.FeedVideos(&video.FeedVideoRequest{})

	resp := new(video.FeedVideoResponse)

	if err != nil {
		e := errno.ConvertErr(err)
		resp.Base = &common.BaseResponse{
			Code: "-1",
			Msg:  e.ErrMsg,
		}
		c.JSON(consts.StatusOK, resp)
		return
	}

	resp.Base = &common.BaseResponse{
		Code: fmt.Sprintf("%d", errno.Success.ErrCode), // 10000
		Msg:  errno.Success.ErrMsg,                     // "success"
	}
	resp.Data = &common.VideoDataForPopularResponse{
		Items: pack.Videos(videos),
	}

	c.JSON(consts.StatusOK, resp)
}
