// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	user "github.com/ShaddockNH3/west2-online-golang-2025-test/test/hertz_gateway_example/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)
}
