// Code generated by hertz generator.

package interact

import (
	"context"

	"github.com/ShaddockNH3/west2-online-golang-2025-test/task4/biz/mw/jwt"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		TokenTransferMiddleware(),
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _listcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishcommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		TokenTransferMiddleware(),
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _actionlikeMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		TokenTransferMiddleware(),
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _listlikeMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		TokenTransferMiddleware(),
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func TokenTransferMiddleware() app.HandlerFunc {
	return func(c context.Context, ctx *app.RequestContext) {
		accessToken := string(ctx.Request.Header.Peek("Access-Token"))

		if accessToken != "" {
			ctx.Request.Header.Set("Authorization", "Bearer "+accessToken)
		}

		ctx.Next(c)
	}
}
